# -*- coding: utf-8 -*-
"""yok ML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qu_jYKRJmCvJ0RdIBbQjxruB1n_cuMD6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

customer_data = pd.read_csv('/content/Mall_Customers.csv')
customer_data.head()

customer_data.shape

customer_data.info()

customer_data.isnull().sum()

"""Chossing annual income column and spending score

"""

X = customer_data.iloc[:,[3,4]].values
print(X)

"""chossing the number of clusters"""

WCSS-Within Clusters Sum of Squares

WCSS = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
  kmeans.fit(X)

  WCSS.append(kmeans.inertia_)

sns.set()
plt.plot(range(1,11),WCSS)
plt.title('the elbow point graph')
plt.xlabel('No of clusters')
plt.ylabel('WCSS')
plt.show()

"""Optimam number of clusters = 5

Training the k-means clustering model:
"""

kmeans = KMeans(n_clusters=5, init='k-means++', random_state=0)

#return a label for each data point based on their cluster
Y = kmeans.fit_predict(X)
print(Y)

#plotting all their clusters and their centroids

plt.figure(figsize=(8,8))
plt.scatter(X[Y==0,0],X[Y==0,1], s=50, c='green', label='cluster 1')
plt.scatter(X[Y==1,0],X[Y==1,1], s=50, c='blue', label='cluster 1')
plt.scatter(X[Y==2,0],X[Y==2,1], s=50, c='black', label='cluster 1')
plt.scatter(X[Y==3,0],X[Y==3,1], s=50, c='yellow', label='cluster 1')
plt.scatter(X[Y==4,0],X[Y==4,1], s=50, c='pink', label='cluster 1')

plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], s=100, c='cyan', label='centroid')
plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Scores')
plt.show()





